version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "npm"
    labels:
      - "npm dependencies"
    assignees:
      - "ZakHargz"
    reviewers:
      - "ZakHargz"
    versioning-strategy: widen
    
